[package]
name = "test-makefile"
version = "0.1.0"
authors = ["crocme10 <matt@area403.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
